// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_gen.go

package concordia

type Error uint32
type Mode uint32
type Endian uint32

const (
	ErrOk			= 0x0
	ErrOOB			= 0x1
	ErrInvalidOp		= 0x2
	ErrValidation		= 0x3
	ErrCallback		= 0x4
	ErrStackOverflow	= 0x5
	ErrStackUnderflow	= 0x6
)

const (
	ModeEncode	= 0x0
	ModeDecode	= 0x1
)

const (
	OpNoop		= 0x0
	OpSetEndianLe	= 0x1
	OpSetEndianBe	= 0x2
	OpEnterStruct	= 0x3
	OpExitStruct	= 0x4
	OpMetaVersion	= 0x5
	OpCtxQuery	= 0x6
	OpMetaName	= 0x7

	OpIoU8		= 0x10
	OpIoU16		= 0x11
	OpIoU32		= 0x12
	OpIoU64		= 0x13
	OpIoI8		= 0x14
	OpIoI16		= 0x15
	OpIoI32		= 0x16
	OpIoI64		= 0x17
	OpIoF32		= 0x18
	OpIoF64		= 0x19
	OpIoBool	= 0x1a

	OpIoBitU	= 0x20
	OpIoBitI	= 0x21
	OpIoBitBool	= 0x22
	OpAlignPad	= 0x23
	OpAlignFill	= 0x24

	OpStrNull	= 0x30
	OpStrPreU8	= 0x31
	OpStrPreU16	= 0x32
	OpStrPreU32	= 0x33
	OpArrFixed	= 0x34
	OpArrPreU8	= 0x35
	OpArrPreU16	= 0x36
	OpArrPreU32	= 0x37
	OpArrEnd	= 0x38
	OpRawBytes	= 0x39
)
