// Code generated by gen_bindings.c; DO NOT EDIT.
package concordia

type Error int
type Mode int
type Trans int
type OpCode uint8

const (
	ErrOk Error = 0
	ErrOOB Error = 1
	ErrInvalidOp Error = 2
	ErrValidation Error = 3
	ErrCallback Error = 4
	ErrStackOverflow Error = 5
	ErrStackUnderflow Error = 6
)

const (
	ModeEncode Mode = 0
	ModeDecode Mode = 1
)

const (
	TransNone Trans = 0
	TransScaleF64 Trans = 1
	TransAddI64 Trans = 2
	TransSubI64 Trans = 3
	TransMulI64 Trans = 4
	TransDivI64 Trans = 5
	TransPoly Trans = 6
	TransSpline Trans = 7
)

const (
	OpNoop OpCode = 0x00
	OpSetEndianLe OpCode = 0x01
	OpSetEndianBe OpCode = 0x02
	OpEnterStruct OpCode = 0x03
	OpExitStruct OpCode = 0x04
	OpMetaVersion OpCode = 0x05
	OpCtxQuery OpCode = 0x06
	OpMetaName OpCode = 0x07
	OpIoU8 OpCode = 0x10
	OpIoU16 OpCode = 0x11
	OpIoU32 OpCode = 0x12
	OpIoU64 OpCode = 0x13
	OpIoI8 OpCode = 0x14
	OpIoI16 OpCode = 0x15
	OpIoI32 OpCode = 0x16
	OpIoI64 OpCode = 0x17
	OpIoF32 OpCode = 0x18
	OpIoF64 OpCode = 0x19
	OpIoBool OpCode = 0x1A
	OpIoBitU OpCode = 0x20
	OpIoBitI OpCode = 0x21
	OpIoBitBool OpCode = 0x22
	OpAlignPad OpCode = 0x23
	OpAlignFill OpCode = 0x24
	OpStrNull OpCode = 0x30
	OpStrPreU8 OpCode = 0x31
	OpStrPreU16 OpCode = 0x32
	OpStrPreU32 OpCode = 0x33
	OpArrFixed OpCode = 0x34
	OpArrPreU8 OpCode = 0x35
	OpArrPreU16 OpCode = 0x36
	OpArrPreU32 OpCode = 0x37
	OpArrEnd OpCode = 0x38
	OpRawBytes OpCode = 0x39
	OpConstCheck OpCode = 0x40
	OpConstWrite OpCode = 0x41
	OpRangeCheck OpCode = 0x42
	OpScaleLin OpCode = 0x43
	OpCRC16 OpCode = 0x44
	OpTransAdd OpCode = 0x45
	OpTransSub OpCode = 0x46
	OpTransMul OpCode = 0x47
	OpTransDiv OpCode = 0x48
	OpCRC32 OpCode = 0x49
	OpMarkOptional OpCode = 0x4A
	OpEnumCheck OpCode = 0x4B
	OpTransPoly OpCode = 0x4C
	OpTransSpline OpCode = 0x4D
	OpJumpIfNot OpCode = 0x50
	OpSwitch OpCode = 0x51
	OpJump OpCode = 0x52
	OpLoadCtx OpCode = 0x60
	OpPushImm OpCode = 0x61
	OpPop OpCode = 0x62
	OpBitAnd OpCode = 0x63
	OpBitOr OpCode = 0x64
	OpBitXor OpCode = 0x65
	OpBitNot OpCode = 0x66
	OpShl OpCode = 0x67
	OpShr OpCode = 0x68
	OpEq OpCode = 0x69
	OpNeq OpCode = 0x6A
	OpGt OpCode = 0x6B
	OpLt OpCode = 0x6C
	OpGte OpCode = 0x6D
	OpLte OpCode = 0x6E
	OpLogAnd OpCode = 0x6F
	OpLogOr OpCode = 0x70
	OpLogNot OpCode = 0x71
)

const (
	Le = 0
	Be = 1
)
